services:
  mysql:
    image: mysql:8.0
    container_name: quarkus-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quarkusdb
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql_data: